#!/bin/zsh


dir=`dirname "$0"`
source $dir/dimcfg

export HOME=/home/$i
export XAUTHORITY=/home/$i/.Xauthority
export DISPLAY=:0.0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
export XDG_RUNTIME_DIR=/run/user/1000

source /home/$i/.zshrc


IFS=$' '
getBatteryStatus | {
  read -r capacity state 
  # if there is something discharging.
  if [ -e ~/.config/i3/config ]; then 
    if [ "$state" = "Discharging" ]; then
      id=$(diff ~/.config/i3/config.low ~/.config/i3/config)
      if [ "$id" != "" ]; then
        ln -s ~/.config/i3/config.low ~/.config/i3/config -f
        i3-msg reload
      fi
    else
      id=$(diff ~/.config/i3/config.standard ~/.config/i3/config)
      if [ "$id" != "" ]; then
        ln -s ~/.config/i3/config.standard ~/.config/i3/config -f
        i3-msg reload
      fi
    fi
  else
    if [ "$state" = "Discharging" ]; then
      ln -s ~/.config/i3/config.low ~/.config/i3/config -f
    else
      ln -s ~/.config/i3/config.standard ~/.config/i3/config -f
    fi
  fi


  if [ "$capacity" != "" ]; then
    if [ "$state" = "Discharging" ]; then

      #
      # Level WARNING
      #
      if [ $capacity -lt 10 ]; then 
        f=~/.energyAlert
        maxAge=300
        age=0
        if [ ! -f $f ]; then
          age=$maxAge
        else
          age=$(($(date +%s) - $(date +%s -r $f)))
        fi
        if [ $age -ge $maxAge ]; then
          notify-send --urgency=critical "WARNING: energy = ($capacity)! Disable warning for $maxAge seconds by touching ~/.energyAlert!";
          for i in {1..3}
          do
            xrandr --output eDP-1 --display :0 --brightness 2.0 --gamma 0.0:0.0:0.0
            sleep .1
            xrandr --output eDP-1 --display :0 --brightness 1.0 --gamma 0.0:0.0:0.0
            sleep .1 
          done
        fi

      #
      # Level Warning 2  
      # 
      elif [ $capacity -lt 20 ]; then
        f=~/.energyWarning
        maxAge=600
        if [ ! -f $f ]; then
          age=$maxAge
        else
          age=$(($(date +%s) - $(date +%s -r $f)))
        fi
        if [ $age -ge $maxAge ]; then
          touch $f
          notify-send "Energy warning: $capacity";
          for i in {1..1}
          do
            xrandr --output eDP-1 --display :0 --brightness 2.0 --gamma 0.0:0.0:0.0
            sleep .3
            xrandr --output eDP-1 --display :0 --brightness 1.0 --gamma 0.0:0.0:0.0
            sleep .3 
          done
        fi

      #
      # Level Info
      # 
      elif [ $capacity -lt 30 ]
      then
        f=~/.energyInfo
        maxAge=1200
        age=0
        if [ ! -f $f ]; then
          age=$maxAge
        else
          age=$(($(date +%s) - $(date +%s -r $f)))
        fi
        if [ $age -ge $maxAge ]; then
          touch $f
          notify-send "Energy info $capacity.";
          for i in {1}
          do
            xrandr --output eDP-1 --display :0 --brightness 2.0 --gamma 0.0:0.0:0.0
            sleep .1
            xrandr --output eDP-1 --display :0 --brightness 1.0 --gamma 0.0:0.0:0.0
          done
        fi
      fi
    fi
  fi

  mkdir -p ~/.batteryStats/
  echo -n "$capacity\t$state\t$(date +%s)\n" >> ~/.batteryStats/stats
}
