#!/bin/zsh


mem=$(free --giga | awk '/^Mem:/ {print $4}')

if (( $mem <= 1 )); then 
  notify-send --urgency=critical "WARNING: only $mem GB processing memory left";
elif (( $mem <= 2 )); then 
  notify-send  "WARNING: only $mem GB processing memory left";
#elif (( $mem <= 13 )); then 
#  notify-send  "WARNING: only $mem GB processing memory left";
fi



