#!/bin/bash

# Create a screenshot that captures a selectable rectangle of the screen.
# In my i3-wm, scrot -s does not correctly remove the borders of the rectangle selection, otherwise
# scrot -s could be used directly.

read -r x y w h G ID < <(slop -f "%x %y %w %h %g %i")
sleep 2
mkdir -p ~/Screenshots/
filename=~/Screenshots/"$(date '+%Y-%m-%d-%H%M%S').png"
scrot -a $x,$y,$w,$h -f $filename

xclip -selection clipboard -t image/png -i $filename





