#!/bin/sh

# Powermanagement
name=$(whoami)
name="x"
powertop --auto-tune
sudo chown $name:$name /sys/class/backlight/intel_backlight/brightness


if [ -L /mnt/data/scripts ]; then
  echo "remoging and recreating."
  rm /mnt/data/scripts
fi

if [ -d /mnt/data/scripts ]; then
  echo "x"
else
  echo "n"
  ln -s /home/$name/scripts/scripts /mnt/data/scripts
  echo $name
  sudo chown $name:$name /mnt/data/scripts -R
fi

