#!/bin/zsh

dir=`dirname "$0"`
source "$dir/dimcfg"

# Powermanagement
powertop --auto-tune
sudo chown $i:$i /sys/class/backlight/intel_backlight/brightness
if [ -d /sys/class/leds/smc::kbd_backlight ]; then
  sudo chown $i:$i /sys/class/leds/smc::kbd_backlight/brightness
fi


if [ -L /mnt/data/scripts ]; then
  rm /mnt/data/scripts
fi

if [ -d /mnt/data/scripts ]; then
else
  ln -s /home/$i/scripts/scripts /mnt/data/scripts
  sudo chown $i:$i /mnt/data/scripts -R
fi

